#!/usr/bin/env python3

import argparse
import hashlib
import struct
import sys

IMAGE_HASH_MAGIC = 0x48415348  # "HASH"


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Append ImageHash suffix (magic + SHA-256) to a firmware binary."
    )
    parser.add_argument("input", help="Input binary file")
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="Output file with ImageHash suffix appended",
    )
    args = parser.parse_args()

    with open(args.input, "rb") as f:
        firmware = f.read()

    sha256 = hashlib.sha256(firmware).digest()
    suffix = struct.pack("<I", IMAGE_HASH_MAGIC) + sha256

    with open(args.output, "wb") as f:
        f.write(firmware)
        f.write(suffix)


if __name__ == "__main__":
    main()
